#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="plots.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "gate_final.csv")],
        target=[
            ctx.path_to(ctx, "OUT_FIGURES", "matrix_nan.png"),
            ctx.path_to(ctx, "OUT_FIGURES", "heatmap_nan.png"),
        ],
        name="plots",
    )

    for d in (
        "chisq_df",
        "integrity_df",
        "levene_df",
        "logistic_df",
        "welch_df",
        "gate_complete_controls_coeff",
        "gate_complete_controls_summary",
        "gate_complete_no_controls_coeff",
        "gate_complete_no_controls_summary",
        "data_imputed_kNN_controls_coeff",
        "data_imputed_kNN_controls_summary",
        "data_imputed_kNN_msd_controls_coeff",
        "data_imputed_kNN_msd_controls_summary",
        "data_imputed_kNN_max_controls_coeff",
        "data_imputed_kNN_max_controls_summary",
        "data_imputed_kNN_min_controls_coeff",
        "data_imputed_kNN_min_controls_summary",
    ):
        ctx(
            features="run_py_script",
            source="tables.py",
            deps=[
                ctx.path_to(ctx, "OUT_ANALYSIS", d + ".csv"),
                ctx.path_to(ctx, "IN_AUXILIARY", "formatting.py"),
                ctx.path_to(ctx, "IN_AUXILIARY", "pretty_index.py"),
            ],
            target=[ctx.path_to(ctx, "OUT_TABLES", "table_" + d + ".tex")],
            name="tables",
        )
