#! python


def build(ctx):
    ctx(
        features="run_py_script",
        source="missing_analysis.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "gate_final.csv")],
        target=[
            ctx.path_to(ctx, "OUT_TABLES", "table_integrity.tex"),
            ctx.path_to(ctx, "OUT_TABLES", "table_missing.tex"),
            ctx.path_to(ctx, "OUT_TABLES", "table_levene.tex"),
            ctx.path_to(ctx, "OUT_TABLES", "table_chisq.tex"),
        ],
        name="missing_analysis",
    ),
    ctx(
        features="run_py_script",
        source="missing_plots.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "gate_final.csv")],
        target=[
            ctx.path_to(ctx, "OUT_FIGURES", "matrix_nan.png"),
            ctx.path_to(ctx, "OUT_FIGURES", "heatmap_nan.png"),
        ],
        name="missing_plots",
    )
