def build(ctx):

    ctx(
        features="run_py_script",
        source="impute.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "gate_final.csv")],
        target=[
            ctx.path_to(ctx, "OUT_DATA", "data_imputed_v1.csv"),
            ctx.path_to(ctx, "OUT_DATA", "data_imputed_v2.csv"),
        ],
        name="impute",
    )
