"""Dictionary to be used as tables' new index."""

pretty_index_dict = {
    "constant": "intercept",
    "treatment": "Treatment",
    "philadelphia": "Philadelphia",
    "pittsburgh": "Pittsburgh",
    "minneapolis": "Minneapolis",
    "duluth": "Duluth",
    "maine": "Maine",
    "age": "Age",
    "age_p25": "35 or younger",
    "age_p25_75": "Between 35 and 50",
    "age_p75": "50 or older",
    "grade": "Highest grade achieved",
    "grade_p25": "High-school or less",
    "grade_p25_75": "Some college education",
    "grade_p75": "Bachelor's degree or more",
    "female": "Female",
    "married": "Married",
    "children": "Has children",
    "not_born_us": "Not born in the US",
    "nonenglish": "Not an English native speaker",
    "white": "White",
    "black": "Black",
    "asian": "Asian",
    "latino": "Latino",
    "other": "Other race",
    "healthproblem": "Has an health problem",
    "employer_healthins": "Health insurance provided by employer",
    "self_employed": "Is self-employed",
    "unemployed": "Unemployed",
    "salaried_worker": "Salaried worker",
    "worked_for_relatives_friends_se": "Worked for self-employed friends",
    "benefits": "Receives unemployment benefits",
    "hhincome_25k": "Yearly income lower than 25k",
    "hhincome_25_49k": "Yearly income between 25k and 49k",
    "hhincome_50_74k": "Yearly income between 50k and 74k",
    "hhincome_75_99k": "Yearly income between 75k and 99k",
    "hhincome_100k": "Yearly income higher than 100k",
    "badcredit": "Has bad credit history",
    "autonomy_std": "Standardized autonomy index",
    "risk_tolerance_std": "Standardized risk-tolerance index",
    "low_autonomy_std": "Low autonomy index",
    "low_risk_tolerance_std": "Low risk-tolerance index",
    "sample_size": "Sample size",
    "completed_w2": "Percent of baseline sample",
    "missing_cov": "Missing value(s) in covariates",
    "missing_out": "Missing value in outcome",
}
