#! python
import os


def build(ctx):
    abspath = os.path.join(ctx.path.abspath(), "test_tables_functions.py")
    ctx(
        features="run_py_script",
        source="test_auxiliary_functions.py",
        deps="auxiliary_functions.py",
        append=abspath,
    )
