#! python
import os


def build(ctx):
    abspath = os.path.join(ctx.path.abspath(), "test_imputation_method.py")
    ctx(
        features="run_py_script",
        source="test_imputation_method.py",
        deps=[ctx.path_to(ctx, "IMPUTATION_METHOD", "imputation_method.py")],
        append=abspath,
    )
