#! python
import os


def build(ctx):
    abspath = os.path.join(ctx.path.abspath(), "test_impute_method.py")
    ctx(
        features="run_py_script",
        source="test_impute_method.py",
        deps=[ctx.path_to(ctx, "METHOD_DEFINE", "impute_method.py")],
        append=abspath,
    )
