#! python


def build(ctx):
    ctx(
        features="run_py_script",
        source="table_ols_controls.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "gate_final.csv")],
        target=[ctx.path_to(ctx, "OUT_TABLES", "table_ols_controls.tex")],
        name="table_ols_controls",
    )
