#! python


def build(ctx):

    for t in ("integrity", "chisq", "levene", "logistic", "welch"):
        ctx(
            features="run_py_script",
            source="missing_mechanism_analysis.py",
            deps=[
                ctx.path_to(ctx, "OUT_DATA", "gate_final.csv"),
                ctx.path_to(ctx, "IN_AUXILIARY", "auxiliary_functions.py"),
            ],
            target=[ctx.path_to(ctx, "OUT_ANALYSIS", t + "_df.csv")],
            name="missing_mechanism_analysis",
        )

    for t in (
        "gate_complete_controls_coeff",
        "gate_complete_controls_summary",
        "gate_complete_no_controls_coeff",
        "gate_complete_no_controls_summary",
    ):
        ctx(
            features="run_py_script",
            source="complete_case_analysis.py",
            deps=[
                ctx.path_to(ctx, "OUT_DATA", "gate_complete.csv"),
                ctx.path_to(ctx, "IN_AUXILIARY", "auxiliary_functions.py"),
            ],
            target=[ctx.path_to(ctx, "OUT_ANALYSIS", t + ".csv")],
            name="complete_case_analysis",
        )
