#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="impute.py",
        deps=[
            ctx.path_to(ctx, "OUT_DATA", "gate_final.csv"),
            ctx.path_to(ctx, "IN_IMPUTATION_METHOD", "imputation_method.py"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_IMPUTED_DATA", "data_imputed_kNN.csv"),
            ctx.path_to(ctx, "OUT_IMPUTED_DATA", "data_imputed_kNN_msd.csv"),
            ctx.path_to(ctx, "OUT_IMPUTED_DATA", "data_imputed_kNN_max.csv"),
            ctx.path_to(ctx, "OUT_IMPUTED_DATA", "data_imputed_kNN_min.csv"),
        ],
        name="impute",
    )
